### ISSUE TITLE
refuge2

### ISSUE THREAD

**Issue by 1390806607** [lin-tianyu/Stable-Diffusion-Seg#18]
@lin-tianyu  Hi, would you like to share the code for the refuge2 preprocessing part? I can't find the code for the preprocessing part

**Comment by lin-tianyu** [comment]
Hi, as the README says, the preprocessing code is provided here: https://github.com/HzFu/MNet_DeepCDR
Take a look at their repo/paper and you'll know how to preprocess, thank you!

**Comment by lin-tianyu** [comment]
You need to modify this specific file for preprocessing: https://github.com/HzFu/MNet_DeepCDR/blob/master/mnet_deep_cdr/Step_1_Disc_Crop.py

**Comment by 1390806607** [comment]
thanks

**Comment by 1390806607** [comment]
@lin-tianyu I reported the following error when using the code to reproduce, can you help me to see how to solve it? I have been vexed with this question for several days  

(sdseg) ➜ Stable-Diffusion-Seg python -u main.py --base configs/latent-diffusion/refuge2-ldm-kl-8-concat-mode.yaml -t --gpus 0 --name test1 
Global seed set to 23
Running on GPUs 0
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 294.97 M params.
Keeping EMAs of 522.
Restored KL-first-stage-model from models/first_stage_models/kl-f8/model.ckpt with 0 missing and 56 unexpected keys
Restored Conditioning-model from models/first_stage_models/kl-f8/model.ckpt with 0 missing and 0 unexpected keys
[ATT]: filling zeros to initialize pretrained weight 'input_blocks.0.0.weight' from torch.Size([192, 4, 3, 3]) to torch.Size([192, 8, 3, 3])
Restored only Diffusion Model from models/ldm/lsun_churches256/model.ckpt with 0 missing and 0 unexpected keys
Monitoring val_avg_dice as checkpoint metric.
Merged modelckpt-cfg: 
{'target': 'pytorch_lightning.callbacks.ModelCheckpoint', 'params': {'dirpath': 'logs/2024-11-24T11-47-55_test1/checkpoints', 'verbose': True, 'save_last': True, 'every_n_train_steps': 1, 'monitor': 'val_avg_dice', 'save_top_k': 1, 'mode': 'max'}}
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
[Dataset]: REFUGE-2 with 2 classes, in train mode
[Dataset]: REFUGE-2 with 2 classes, in test mode
[Dataset]: REFUGE-2 with 2 classes, in train mode
[Dataset]: REFUGE-2 with 2 classes, in test mode
#### Data #####
train, REFUGE2Train, 400
validation, REFUGE2Validation, 400
accumulate_grad_batches = 1
Setting learning rate to 4.00e-05 = 1 (accumulate_grad_batches) * 1 (num_gpus) * 4 (batchsize) * 1.00e-05 (base_lr)
/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:423: LightningDeprecationWarning: DataModule.setup has already been called, so it will not be called again. In v1.6 this behavior will change to always call DataModule.setup.
  rank_zero_deprecation(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
LatentDiffusion: Also optimizing conditioner params!
Setting up LambdaLR scheduler...
Project config
model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    num_classes: 2
    load_only_unet: true
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: segmentation
    cond_stage_key: image
    conditioning_key: concat
    image_size: 32
    channels: 4
    cond_stage_trainable: true
    concat_mode: true
    scale_by_std: true
    use_ema: true
    monitor: val_avg_dice
    ckpt_path: models/ldm/lsun_churches256/model.ckpt
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 10000
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 8
        out_channels: 4
        model_channels: 192
        attention_resolutions:
        - 1
        - 2
        - 4
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 2
        - 4
        - 4
        num_heads: 8
        use_scale_shift_norm: true
        resblock_updown: true
        dropout: 0.2
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ckpt_path: models/first_stage_models/kl-f8/model.ckpt
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.AEEncoderEmbedder
      params:
        ckpt_path: models/first_stage_models/kl-f8/model.ckpt
        embed_dim: 4
        double_z: true
        z_channels: 4
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult:
        - 1
        - 2
        - 4
        - 4
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.2
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.refuge2.REFUGE2Train
      params:
        size: 256
        num_classes: 2
    validation:
      target: ldm.data.refuge2.REFUGE2Validation
      params:
        size: 256
        num_classes: 2

Lightning config
callbacks:
  image_logger:
    target: main.ImageLogger
    params:
      batch_frequency: 1
      max_images: 8
      increase_log_steps: false
      log_dice_frequency: 1
trainer:
  benchmark: true
  check_val_every_n_epoch: 5
  accelerator: gpu
  gpus:
  - 0


  | Name              | Type              | Params
--------------------------------------------------------
0 | model             | DiffusionWrapper  | 294 M 
1 | model_ema         | LitEma            | 0     
2 | first_stage_model | AutoencoderKL     | 83.7 M
3 | cond_stage_model  | AEEncoderEmbedder | 34.2 M
--------------------------------------------------------
329 M     Trainable params
83.7 M    Non-trainable params
412 M     Total params
1,651.165 Total estimated model params size (MB)
Global seed set to 23                                                                                                                                                                                                         
Epoch 0:   0%|                                                                                                                                                                              | 0/100 [00:00<00:00, 4266.84it/s]setting self.scale_factor to 0.11453842371702194
### USING STD-RESCALING: True ###
[logging class ID]: tensor([-1, -1, -1, -1])
Plotting: Switched to EMA weights
Plotting: Restored training weights
Plotting Progressives: Switched to EMA weights
Progressive Generation: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:40<00:00, 24.88it/s]
Plotting Progressives: Restored training weights██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 999/1000 [00:40<00:00, 25.49it/s]
Progressive Generation: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 24.70it/s]
> /home/featurize/work/Stable-Diffusion-Seg/main.py(382)log_img()███████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 5/6 [00:00<00:00, 37.97it/s]
-> self.log_local(pl_module.logger.save_dir, split, images,
(Pdb) c
Epoch 0:   1%|▊                                                                             | 1/100 [01:00<49:39, 30.09s/it, loss=0.376, v_num=0, train/loss_seg=0.190, train/loss_simple=0.186, train/loss=0.376, step=0.000]Epoch 0, global step 0: val_avg_dice reached 0.00000 (best 0.00000), saving model to "logs/2024-11-24T11-47-55_test1/checkpoints/epoch=0-step=0.ckpt" as top 1
end finally

Traceback (most recent call last):
  File "main.py", line 817, in <module>
    trainer.fit(model, data)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1045, in _run_train
    self.fit_loop.run()
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 150, in advance
    self.trainer.call_hook(
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1217, in call_hook
    trainer_hook(*args, **kwargs)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 189, in on_train_batch_end
    callback.on_train_batch_end(self, self.lightning_module, outputs, batch, batch_idx, dataloader_idx)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 296, in on_train_batch_end
    self.save_checkpoint(trainer)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 384, in save_checkpoint
    self._save_top_k_checkpoint(trainer, monitor_candidates)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 731, in _save_top_k_checkpoint
    self._update_best_and_save(current, trainer, monitor_candidates)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 794, in _update_best_and_save
    self._save_model(trainer, filepath)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 540, in _save_model
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/properties.py", line 399, in save_checkpoint
    self.checkpoint_connector.save_checkpoint(filepath, weights_only)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 441, in save_checkpoint
    self.trainer.accelerator.save_checkpoint(_checkpoint, filepath)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 484, in save_checkpoint
    self.training_type_plugin.save_checkpoint(checkpoint, filepath)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 267, in save_checkpoint
    atomic_save(checkpoint, filepath)
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/pytorch_lightning/utilities/cloud_io.py", line 65, in atomic_save
    f.write(bytesbuffer.getvalue())
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/fsspec/core.py", line 134, in __exit__
    self.close()
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/fsspec/core.py", line 154, in close
    f.close()
  File "/environment/miniconda3/envs/sdseg/lib/python3.8/site-packages/fsspec/implementations/local.py", line 444, in close
    return self.f.close()
OSError: [Errno 5] Input/output error

**Comment by lin-tianyu** [comment]
Hi,

I have never encountered this error. It seems that the error occurs when trying to save the model weights. In this case, I can only assume the environment that you run the code has some Disk Space issue or Path and Permission issue. So please make sure your device has enough disk space (typically 5GB for a model weight) and you have the right permission to write the path.

What's more, you can set the `log_first_step=False` in: https://github.com/lin-tianyu/Stable-Diffusion-Seg/blob/9a6af6065a5f7dbe35a8ebe45e503ded4caadd1a/main.py#L307
In this case you will not run the logging process every time you start the training. This will save you some time during debugging. 

Best,
Tianyu


## Appendix
This is what ChatGPT 4o gives me regarding your traceback. Hope this helps:

The OSError: [Errno 5] Input/output error typically occurs when the system encounters an issue writing to a file or accessing a specific location during training in PyTorch Lightning. Here are some potential causes and solutions:

Potential Causes

1. Storage Issues:
	- Insufficient disk space.
	- File system errors or corrupted directories.
	- Temporary unavailability of the storage medium.
2. Permissions:
	- The checkpoint directory or file path might lack write permissions.
3. Networked Filesystem:
	- If the checkpoint is being saved to a network-mounted drive or distributed filesystem (e.g., NFS, Lustre), there might be latency or disconnection issues.
4. Concurrency Issues:
	- Another process might be accessing the same file or directory, causing a conflict.
5. Disk Hardware Issues:
	- Physical problems with the disk can cause intermittent I/O errors.

Solutions

1. Check Disk Space

	•	Ensure that there is sufficient space available in the checkpoint directory.

df -h


	•	If the disk is full, free up some space or redirect your checkpoints to a different location.

2. Verify File Path and Permissions

	•	Ensure that the directory where the checkpoints are being saved exists and is writable:

chmod -R 777 /path/to/checkpoint/dir


	•	If using a shared or network-mounted drive, confirm you have the required permissions.

3. Change the Checkpoint Path

	•	Redirect the checkpoint directory to a local, stable path (e.g., /tmp):

trainer = pl.Trainer(default_root_dir="/tmp/checkpoints")



4. Use Robust Checkpointing

	•	Disable or minimize frequent checkpointing if disk I/O is unstable:

checkpoint_callback = pl.callbacks.ModelCheckpoint(
    save_top_k=1,  # Keep only the best checkpoint
    monitor="val_loss",  # Monitor your chosen metric
    mode="min",
    every_n_epochs=1,  # Save only once per epoch
)
trainer = pl.Trainer(callbacks=[checkpoint_callback])



5. Avoid Networked Storage

	•	If you’re using a networked or distributed filesystem, consider saving checkpoints locally and transferring them later.

6. Check for Concurrency Issues

	•	Ensure no other process is writing to or accessing the checkpoint file or directory at the same time.

7. Monitor Disk Health

	•	Check for hardware issues using tools like fsck (for Linux) or chkdsk (for Windows).

8. Debug Logging

	•	Enable more detailed logging to understand where the issue is occurring:

trainer = pl.Trainer(
    log_every_n_steps=10,
    enable_progress_bar=True,
    enable_checkpointing=True,
    logger=True,
)

Next Steps

If the issue persists:
	•	Test saving a dummy file to the checkpoint directory during training to confirm its accessibility.
	•	Share additional details, such as the storage setup (local, network, cloud) and specific environment configurations.

By addressing these areas, you should be able to identify and resolve the I/O issue affecting your training workflow.

**Comment by 1390806607** [comment]
@lin-tianyu  Epoch 0, global step 0: val_avg_dice reached 0.00000 (best 0.00000), saving model to "logs/2024-11-24T11-47-55_test1/checkpoints/epoch=0-step=0.ckpt" as top 1
end finally     Is this piece normal? My current test is an epoch and I will verify it, but its dice is 0?

**Comment by lin-tianyu** [comment]
as the paper described, we trained dozens of thousands of steps for a segmentation model. A single epoch contains only 100 steps in your case. so yeah,  it is normal to get dice==0 in the first epoch
